"""russian lang at search of profiles

Revision ID: 03aaa0e2cdfd
Revises: f0b9c9af1201
Create Date: 2026-05-22 19:52:49.016425

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03aaa0e2cdfd"
down_revision: Union[str, Sequence[str], None] = "f0b9c9af1201"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_profiles_displayed_name_trgm",
        "profiles",
        ["displayed_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"displayed_name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_profiles_displayed_name_trgm",
        table_name="profiles",
        postgresql_using="gin",
        postgresql_ops={"displayed_name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
