"""profile_id indexes at posts and albums

Revision ID: 0a20dc85a0df
Revises: c3d6a1b7f4e9
Create Date: 2026-05-24 01:44:11.247121

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0a20dc85a0df"
down_revision: Union[str, Sequence[str], None] = "c3d6a1b7f4e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_albums_profile_id",
        "albums",
        ["profile_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.alter_column(
        "posts",
        "search_vector",
        existing_type=postgresql.TSVECTOR(),
        nullable=False,
        existing_server_default=sa.Computed(
            "(((setweight(to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying))::text), 'A'::\"char\") || setweight(to_tsvector('english'::regconfig, (COALESCE(content, ''::character varying))::text), 'B'::\"char\")) || setweight(to_tsvector('russian'::regconfig, (COALESCE(title, ''::character varying))::text), 'A'::\"char\")) || setweight(to_tsvector('russian'::regconfig, (COALESCE(content, ''::character varying))::text), 'B'::\"char\"))",
            persisted=True,
        ),
    )
    op.create_index(
        "ix_posts_profile_id",
        "posts",
        ["profile_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.alter_column(
        "profiles",
        "search_vector",
        existing_type=postgresql.TSVECTOR(),
        nullable=False,
        existing_server_default=sa.Computed(
            "(((setweight(to_tsvector('english'::regconfig, (COALESCE(displayed_name, ''::character varying))::text), 'A'::\"char\") || setweight(to_tsvector('english'::regconfig, (COALESCE(bio, ''::character varying))::text), 'B'::\"char\")) || setweight(to_tsvector('russian'::regconfig, (COALESCE(displayed_name, ''::character varying))::text), 'A'::\"char\")) || setweight(to_tsvector('russian'::regconfig, (COALESCE(bio, ''::character varying))::text), 'B'::\"char\"))",
            persisted=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles",
        "search_vector",
        existing_type=postgresql.TSVECTOR(),
        nullable=True,
        existing_server_default=sa.Computed(
            "(((setweight(to_tsvector('english'::regconfig, (COALESCE(displayed_name, ''::character varying))::text), 'A'::\"char\") || setweight(to_tsvector('english'::regconfig, (COALESCE(bio, ''::character varying))::text), 'B'::\"char\")) || setweight(to_tsvector('russian'::regconfig, (COALESCE(displayed_name, ''::character varying))::text), 'A'::\"char\")) || setweight(to_tsvector('russian'::regconfig, (COALESCE(bio, ''::character varying))::text), 'B'::\"char\"))",
            persisted=True,
        ),
    )
    op.drop_index("ix_posts_profile_id", table_name="posts", postgresql_using="btree")
    op.alter_column(
        "posts",
        "search_vector",
        existing_type=postgresql.TSVECTOR(),
        nullable=True,
        existing_server_default=sa.Computed(
            "(((setweight(to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying))::text), 'A'::\"char\") || setweight(to_tsvector('english'::regconfig, (COALESCE(content, ''::character varying))::text), 'B'::\"char\")) || setweight(to_tsvector('russian'::regconfig, (COALESCE(title, ''::character varying))::text), 'A'::\"char\")) || setweight(to_tsvector('russian'::regconfig, (COALESCE(content, ''::character varying))::text), 'B'::\"char\"))",
            persisted=True,
        ),
    )
    op.drop_index("ix_albums_profile_id", table_name="albums", postgresql_using="btree")
    # ### end Alembic commands ###
