"""followers

Revision ID: 0f41c4e7ca7b
Revises: ddcde82a7f0b
Create Date: 2026-06-06 01:36:00.121057

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f41c4e7ca7b"
down_revision: Union[str, Sequence[str], None] = "ddcde82a7f0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("follower_id", sa.UUID(), nullable=False),
        sa.Column("followed_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["followed_id"], ["artists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["follower_id"], ["artists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("follower_id", "followed_id", name="uq_follower_followed"),
    )
    op.create_index("ix_follows_created_at", "follows", ["created_at"], unique=False)
    op.create_index("ix_follows_followed_id", "follows", ["followed_id"], unique=False)
    op.create_index("ix_follows_follower_id", "follows", ["follower_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_follows_follower_id", table_name="follows")
    op.drop_index("ix_follows_followed_id", table_name="follows")
    op.drop_index("ix_follows_created_at", table_name="follows")
    op.drop_table("follows")
    # ### end Alembic commands ###
