"""fixing indexes

Revision ID: 1aac353d93ac
Revises: ad4394575e62
Create Date: 2026-05-19 16:51:55.785377

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1aac353d93ac"
down_revision: Union[str, Sequence[str], None] = "ad4394575e62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_created_at"), table_name="posts")
    op.drop_index(op.f("ix_updated_at"), table_name="posts")
    op.create_index(
        "ix_posts_created_at",
        "posts",
        ["created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_posts_updated_at",
        "posts",
        ["updated_at"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_posts_updated_at", table_name="posts", postgresql_using="btree")
    op.drop_index("ix_posts_created_at", table_name="posts", postgresql_using="btree")
    op.create_index(op.f("ix_updated_at"), "posts", ["updated_at"], unique=False)
    op.create_index(op.f("ix_created_at"), "posts", ["created_at"], unique=False)
    # ### end Alembic commands ###
