"""posts

Revision ID: 2b1451052024
Revises: 09d0b022616b
Create Date: 2026-05-19 01:19:37.406993

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b1451052024"
down_revision: Union[str, Sequence[str], None] = "09d0b022616b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "\n            setweight(to_tsvector('english', coalesce(title, '')), 'A') ||\n            setweight(to_tsvector('english', coalesce(content, '')), 'B')\n            ",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_created_at", "posts", ["created_at"], unique=False, postgresql_using="btree"
    )
    op.create_index(
        "ix_posts_search_vector",
        "posts",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_updated_at", "posts", ["updated_at"], unique=False, postgresql_using="btree"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_updated_at", table_name="posts", postgresql_using="btree")
    op.drop_index("ix_posts_search_vector", table_name="posts", postgresql_using="gin")
    op.drop_index("ix_created_at", table_name="posts", postgresql_using="btree")
    op.drop_table("posts")
    # ### end Alembic commands ###
