"""track embedding model 768 vector

Revision ID: 32bc8faa1b0f
Revises: c89a74f20aaa
Create Date: 2026-10-09 01:59:33.533326

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32bc8faa1b0f"
down_revision: Union[str, Sequence[str], None] = "c89a74f20aaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "track_embedding",
        "embedding_vector",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "track_embedding",
        "embedding_vector",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
