"""playlist model

Revision ID: 63b55d157859
Revises: 8b551fc3adcd
Create Date: 2026-05-25 00:11:24.291889

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "63b55d157859"
down_revision: Union[str, Sequence[str], None] = "8b551fc3adcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
