"""likes model

Revision ID: 71813b6dce50
Revises: 0f41c4e7ca7b
Create Date: 2026-06-06 03:07:39.590891

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71813b6dce50"
down_revision: Union[str, Sequence[str], None] = "0f41c4e7ca7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "likes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "TRACK", "RELEASE", "PLAYLIST", "POST", "COMMENTARY", name="targettype"
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_likes_artist_id", "likes", ["artist_id"], unique=False)
    op.create_index("ix_likes_created_at", "likes", ["created_at"], unique=False)
    op.create_index(
        "ix_likes_target_type_target_id",
        "likes",
        ["target_type", "target_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_likes_target_type_target_id", table_name="likes")
    op.drop_index("ix_likes_created_at", table_name="likes")
    op.drop_index("ix_likes_artist_id", table_name="likes")
    op.drop_table("likes")
    # ### end Alembic commands ###
