"""releases statuses and type enum

Revision ID: 812b01bec7d5
Revises: 2e46a64a7915
Create Date: 2026-05-24 02:56:50.205693

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "812b01bec7d5"
down_revision: Union[str, Sequence[str], None] = "2e46a64a7915"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    release_type_enum = sa.Enum("SINGLE", "EP", "ALBUM", name="releasetype")
    release_status_enum = sa.Enum(
        "DRAFT", "SCHEDULED", "PUBLISHED", "DELETED", name="releasestatus"
    )

    release_type_enum.create(op.get_bind(), checkfirst=True)
    release_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "releases",
        sa.Column(
            "release_type",
            release_type_enum,
            nullable=True,
        ),
    )

    op.execute("UPDATE releases SET release_type = 'ALBUM';")
    op.execute("UPDATE releases SET status = UPPER(status);")

    op.alter_column(
        "releases",
        "status",
        existing_type=sa.VARCHAR(),
        type_=release_status_enum,
        postgresql_using="status::releasestatus",
        existing_nullable=False,
    )
    op.alter_column("releases", "release_type", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    release_type_enum = sa.Enum("SINGLE", "EP", "ALBUM", name="releasetype")
    release_status_enum = sa.Enum(
        "DRAFT", "SCHEDULED", "PUBLISHED", "DELETED", name="releasestatus"
    )

    op.alter_column(
        "releases",
        "status",
        existing_type=release_status_enum,
        type_=sa.VARCHAR(),
        postgresql_using="status::text",
        existing_nullable=False,
    )
    op.execute("UPDATE releases SET status = LOWER(status);")
    op.drop_column("releases", "release_type")

    release_type_enum.drop(op.get_bind(), checkfirst=True)
    release_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
