"""tracks and albums

Revision ID: a7233aaf8978
Revises: 1aac353d93ac
Create Date: 2026-05-20 01:44:34.397428

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a7233aaf8978"
down_revision: Union[str, Sequence[str], None] = "1aac353d93ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """CREATE EXTENSION IF NOT EXISTS pg_trgm;"""
    )  # we need pg_trgm for efficient full-text search on profiles, and since the search vector is computed from the displayed_name and bio fields, which are part of the profiles table, it makes sense to create the extension in this migration.

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("picture_path", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_albums_created_at",
        "albums",
        ["created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_albums_deleted_at",
        "albums",
        ["deleted_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_albums_updated_at",
        "albums",
        ["updated_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "tracks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("album_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("genres", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["album_id"], ["albums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tracks_created_at",
        "tracks",
        ["created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_tracks_deleted_at",
        "tracks",
        ["deleted_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.drop_index(op.f("ix_deleted_at"), table_name="profiles")
    op.create_index(
        "ix_profiles_deleted_at",
        "profiles",
        ["deleted_at"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_profiles_deleted_at", table_name="profiles", postgresql_using="btree"
    )
    op.create_index(op.f("ix_deleted_at"), "profiles", ["deleted_at"], unique=False)
    op.drop_index("ix_tracks_deleted_at", table_name="tracks", postgresql_using="btree")
    op.drop_index("ix_tracks_created_at", table_name="tracks", postgresql_using="btree")
    op.drop_table("tracks")
    op.drop_index("ix_albums_updated_at", table_name="albums", postgresql_using="btree")
    op.drop_index("ix_albums_deleted_at", table_name="albums", postgresql_using="btree")
    op.drop_index("ix_albums_created_at", table_name="albums", postgresql_using="btree")
    op.drop_table("albums")
    # ### end Alembic commands ###
