"""index on profiles

Revision ID: ad4394575e62
Revises: 2b1451052024
Create Date: 2026-05-19 01:27:08.281644

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad4394575e62"
down_revision: Union[str, Sequence[str], None] = "2b1451052024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_deleted_at",
        "profiles",
        ["deleted_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_profiles_created_at",
        "profiles",
        ["created_at"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_profiles_created_at", table_name="profiles", postgresql_using="btree"
    )
    op.drop_index("ix_deleted_at", table_name="profiles", postgresql_using="btree")
    # ### end Alembic commands ###
