"""albums statuses like draft and published

Revision ID: b24ae27f9fe8
Revises: 1f0d6c3b8e2a
Create Date: 2026-05-23 01:54:06.146931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b24ae27f9fe8"
down_revision: Union[str, Sequence[str], None] = "1f0d6c3b8e2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("albums", sa.Column("status", sa.String(), nullable=True))
    op.add_column("albums", sa.Column("release_date", sa.DateTime(), nullable=True))
    op.create_index(
        "ix_albums_release_date",
        "albums",
        ["release_date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_albums_status", "albums", ["status"], unique=False, postgresql_using="btree"
    )
    op.alter_column(
        "posts", "search_vector", existing_type=postgresql.TSVECTOR(), nullable=False
    )
    op.alter_column(
        "profiles", "search_vector", existing_type=postgresql.TSVECTOR(), nullable=False
    )

    op.execute("""
        UPDATE albums
        SET status = 'published', release_date = created_at
        """)
    op.alter_column("albums", "status", existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles", "search_vector", existing_type=postgresql.TSVECTOR(), nullable=True
    )
    op.alter_column(
        "posts", "search_vector", existing_type=postgresql.TSVECTOR(), nullable=True
    )
    op.drop_index("ix_albums_status", table_name="albums", postgresql_using="btree")
    op.drop_index(
        "ix_albums_release_date", table_name="albums", postgresql_using="btree"
    )
    op.drop_column("albums", "release_date")
    op.drop_column("albums", "status")
    # ### end Alembic commands ###
