"""updating track model to future

Revision ID: b4c8c537fcf9
Revises: 812b01bec7d5
Create Date: 2026-05-24 03:08:53.061524

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4c8c537fcf9"
down_revision: Union[str, Sequence[str], None] = "812b01bec7d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracks", sa.Column("track_number_in_release", sa.Integer(), nullable=True)
    )
    op.add_column("tracks", sa.Column("play_count", sa.Integer(), nullable=True))
    op.add_column("tracks", sa.Column("like_count", sa.Integer(), nullable=True))
    op.add_column("tracks", sa.Column("bitrate", sa.Integer(), nullable=True))
    op.add_column("tracks", sa.Column("mime_type", sa.String(), nullable=True))
    op.add_column("tracks", sa.Column("waveform_path", sa.String(), nullable=True))

    op.execute("UPDATE tracks SET track_number_in_release = 1;")
    op.execute("UPDATE tracks SET play_count = 0;")
    op.execute("UPDATE tracks SET like_count = 0;")
    op.execute("UPDATE tracks SET bitrate = NULL;")
    op.execute("UPDATE tracks SET mime_type = NULL;")
    op.execute("UPDATE tracks SET waveform_path = NULL;")

    op.alter_column(
        "tracks", "track_number_in_release", existing_type=sa.Integer(), nullable=False
    )
    op.alter_column("tracks", "play_count", existing_type=sa.Integer(), nullable=False)
    op.alter_column("tracks", "like_count", existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracks", "waveform_path")
    op.drop_column("tracks", "mime_type")
    op.drop_column("tracks", "bitrate")
    op.drop_column("tracks", "like_count")
    op.drop_column("tracks", "play_count")
    op.drop_column("tracks", "track_number_in_release")
    # ### end Alembic commands ###
