"""playback events fix

Revision ID: bde9d929d01e
Revises: fde9a5d9260c
Create Date: 2026-05-31 21:50:31.603959

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bde9d929d01e"
down_revision: Union[str, Sequence[str], None] = "fde9a5d9260c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "playback_session_events", sa.Column("session_id", sa.UUID(), nullable=False)
    )
    op.create_index(
        "ix_playback_session_events_session_id",
        "playback_session_events",
        ["session_id"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_playback_session_events_session_id",
        table_name="playback_session_events",
        postgresql_using="btree",
    )
    op.drop_column("playback_session_events", "session_id")
    # ### end Alembic commands ###
