"""tracks trgrm index on title

Revision ID: cd6a9497ade7
Revises: a7233aaf8978
Create Date: 2026-05-20 01:47:38.941398

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd6a9497ade7"
down_revision: Union[str, Sequence[str], None] = "a7233aaf8978"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_tracks_title_trgm",
        "tracks",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_tracks_title_trgm",
        table_name="tracks",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
