"""tracks is not about profile id

Revision ID: eeee41b00107
Revises: cd6a9497ade7
Create Date: 2026-05-20 18:19:26.856917

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eeee41b00107"
down_revision: Union[str, Sequence[str], None] = "cd6a9497ade7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_albums_title_trgm",
        "albums",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_constraint(op.f("tracks_profile_id_fkey"), "tracks", type_="foreignkey")
    op.drop_column("tracks", "profile_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracks",
        sa.Column("profile_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("tracks_profile_id_fkey"),
        "tracks",
        "profiles",
        ["profile_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        "ix_albums_title_trgm",
        table_name="albums",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
