"""playback events

Revision ID: fde9a5d9260c
Revises: e9bc4ae36bc9
Create Date: 2026-05-31 21:46:15.966347

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fde9a5d9260c"
down_revision: Union[str, Sequence[str], None] = "e9bc4ae36bc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playback_session_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("listened_seconds", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("is_paused", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_playback_session_events_is_active",
        "playback_session_events",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_playback_session_events_track_id",
        "playback_session_events",
        ["track_id"],
        unique=False,
    )
    op.create_index(
        "ix_playback_session_events_user_id",
        "playback_session_events",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_playback_session_events_user_id", table_name="playback_session_events"
    )
    op.drop_index(
        "ix_playback_session_events_track_id", table_name="playback_session_events"
    )
    op.drop_index(
        "ix_playback_session_events_is_active", table_name="playback_session_events"
    )
    op.drop_table("playback_session_events")
    # ### end Alembic commands ###
